### PR TITLE
Bump OHIF version + add option to disable servers cache

### PR DESCRIPTION
**Pull request by igoroctaviano**
- Bump OHIF version + add option to disable servers cache

### CODE REVIEW

**Comment by igoroctaviano** [comment]
@Punzo This should fix the cache issue with servers.

Testing steps:
- Run the viewer pointing to some random server (dcmjs.org)
- Update default.js file to point to an invalid server
- Refresh the viewer (without clearing the cache)
- The viewer should fail (config to disable cache worked)
- Try flipping the disableServersCache property to false and try modified the server
- The viewer shouldn't be able to update the servers without cleaning the cache

After testing + reviewing the code, you can merge. Feel free to include more items in this pull request tomorrow morning if you want to bring more stuff to deploy.

**Comment by Punzo** [comment]
> @Punzo This should fix the cache issue with servers.
> 
> Testing steps:
> 
> * Run the viewer pointing to some random server (dcmjs.org)
> * Update default.js file to point to an invalid server
> * Refresh the viewer (without clearing the cache)
> * The viewer should fail (config to disable cache worked)
> * Try flipping the disableServersCache property to false and try modified the server
> * The viewer shouldn't be able to update the servers without cleaning the cache
> 
> After testing + reviewing the code, you can merge. Feel free to include more items in this pull request tomorrow morning if you want to bring more stuff to deploy.

great! I will test on Monday, today feeling a little bit dazy because of teh vaccine shot. Could you please also test and review https://github.com/OHIF/Viewers/pull/2397 ? It would be great if we can add that PR as well into IDC fork. Thanks!

**Review by Punzo — APPROVED** [review]
tested, lgtm!

**Comment by Punzo** [comment]
overdensed by https://github.com/ImagingDataCommons/Viewers/pull/87

**Pull request closed without merging**
