### PR TITLE
Idc update

### PR DESCRIPTION
**Pull request by JamesAPetts**
@pieper 

- Update to master..
- Enable debug extension.
- Enable DICOM Tag Browser extension with mailTo to `support@canceridc.dev`.

### CODE REVIEW

**Comment by pieper** [comment]
LGTM 👍 

@wlongabaugh @fedorov I'm updating the sandbox with this version and the configs to turn off measurements and allow multiple url parameters.

**Comment by pieper** [comment]
Okay, sandbox update complete.  You can test there and merge this if you like what you see.

**Comment by fedorov** [comment]
I left a comment in https://github.com/OHIF/Viewers/issues/1532#issuecomment-694533656 - multiple series doesn't work for me, or I don't know how to use it, but let's go ahead with the update anyway.

**Comment by fedorov** [comment]
@pieper I know it's a silly question, but can we double-check sandbox was indeed updated?

From the comments above, it seems that we should have the following options:
* debug extension
* DICOM tag browser extension
* hover tooltips for the segments/rtstructs
* mailto extension
* split query parameters to support series selection

and I don't see any of the above. could it be a wrong config is used or something?

**Pull request merged**
